name: AYDemo
description: Artitic Yoga Demo Flows.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.0
    #  splashscreen:

    # The following adds the Cupertino Ic¯ˀons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.27
  fluttertoast: ^3.0.3
  http: ^0.12.0
  intl: 0.16.1
#  html2md:
#  #  youtube_api:
  flutter_markdown: ^0.2.0
  flutter_svg: ^0.19.0
#  #  shared_preferences: ^0.4.2
#  shared_preferences: ^0.5.6
#  #  url_launcher: ^5.0.1
#  url_launcher:
#  google_maps_flutter: ^0.5.20+1
#  flutter_linkify: ^2.1.0
#  geolocator: ^3.0.1
  animated_splash: ^1.0.0
#  carousel_slider: ^2.2.1
#  carousel_pro: ^1.0.0
#  get_it: ^3.1.0
#  flutter_sim_country_code: 0.0.3
  connectivity: ^0.4.8+6
  device_id: ^0.2.0
  flutter_udid: 1.0.1
#  video_player: ^0.10.8
  flutter_cache_manager: 1.2.2
#  #  Change to 1.2.2
#  google_api_availability: 2.0.1
  searchable_dropdown:
    git: https://github.com/TudoTech/searchable_dropdown.git
  flutter_webview_plugin:
    git: https://github.com/TudoTech/flutter_webview_plugin.git
  wakelock: ^0.1.4+1
#  #    1.1.3
  device_info: 0.4.2+2
#  #  keyboard_visibility: ^0.5.2
#  #  flutter_keyboard_visibility: 0.7.0
  flutter_keyboard_visibility: 3.2.2
#  ffcache: 0.1.3
#  #  flutter_to_airplay: ^1.0.3
  flutter_windowmanager: 0.0.1+1
  visibility_detector:
  flappy_search_bar: 1.7.2
  month_picker_dialog: ^0.3.2
  responsive_flutter: ^0.0.4
  responsive_framework: 0.0.8
  flutter_device_type: ^0.2.0
  dots_indicator: ^1.2.0

#  native_device_orientation: 0.3.0
#  #  onesignal_flutter: ^2.0.0

  flutter_typeahead: 1.8.8
  basic_utils: ^1.2.0
  flutter_launcher_icons: ^0.7.4
  stack_trace: 1.10.0-nullsafety.1
#  #  stack_trace: 1.10.0
#  #  upgrader: 2.3.0
  store_redirect: 1.0.2
  move_to_background: 1.0.1
  cached_network_image: 2.2.0+1
  flutter_pdfview: ^1.0.0+10
  package_info: 0.4.1
  firebase_analytics: ^5.0.11
  firebase_messaging: ^5.1.4
  #  firebase_dynamic_links: ^0.1.0
#  flutter_datetime_picker:
  font_awesome_flutter: 8.8.1
#  cast: 0.2.0
  permission_handler: ^5.0.0+hotfix.6
  provider: ^4.0.5
  shared_preferences: ^0.5.7+2
  uuid: ^2.0.4
  objectdb: ^1.0.7+1
  jitsi_meet: ^0.2.0
#  share: ^0.6.4+2
  share: ^0.6.4
  flutter_share_me: 0.9.1
#  flutter_airplay_plugin:
#    git: https://github.com/nksteven/FlutterAirplayPlugin.git
#  charts_flutter: 0.9.0
#  syncfusion_flutter_gauges: 18.3.40
  material_design_icons_flutter: 4.0.5655
  flutter_native_timezone: 1.0.4
#  manage_calendar_events: 1.0.3
#  flutter_app_badger: ^1.1.2
  ext_video_player: 0.0.6
#  flutter_rtmp_publisher: ^0.0.1
  flutter_vlc_player: 5.0.5
  flutter_zoom_plugin:
    path: ../../flutter_zoom_plugin-master/flutter_zoom_plugin-master
#    git:
#      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
#      ref: 0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
